import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import { Gloock, Special_Elite as SpecialElite } from 'next/font/google';
import './globals.css';

const gloock = Gloock({
  weight: '400',
  variable: '--font-gloock',
  subsets: ['latin'],
});

const specialEliteFont = SpecialElite({
  weight: '400',
  variable: '--font-special-elite',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${specialEliteFont.variable} ${gloock.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
